### ISSUE TITLE
Updating from 0.5

### ISSUE THREAD

**Issue by Jhyrachy** [bfabiszewski/ulogger-server#128]
Hi,
I have a 0.5 server, is there any difference from updating from 0.6?

Also, is there any easy way to updating if I'm using docker?

Thanks!

**Comment by bfabiszewski** [comment]
Main difference between 0.5 and 0.6 is database driver: PDO instead of mysqli. So migration script will fail because it uses previous configuration file.
You will have to manually update database to new schema. Update config.php file (only database settings, PDO format). There are instructions for manual upgrade in [README](https://github.com/bfabiszewski/ulogger-server#upgrade-to-version-1x).

**Comment by bfabiszewski** [comment]
I will close it now. If you have problems, please reopen.

**Comment by Jhyrachy** [comment]
Sure, thanks a lot.
I had no tiem to try, will do it in the next few days
