### ISSUE TITLE
Feature request: share a track one time with a guest.

### ISSUE THREAD

**Issue by alaskalinuxuser** [bfabiszewski/ulogger-server#142]
Thanks for this server and app combo! I love ulogger and use it all the time!

Is it possible to enable a way to share a one time link or one time log in to someone?

For example: I had to drive 260 miles into the middle of nowhere in Alaska to pick up a canoe expedition. I logged my trip in ulogger. Now I need someone else to go there, but I don't want them to have a log in to my server. I also don't want to show them my other trips, just the one.

If I export the track and send it to them, the user needs to know how to import it to something. They also won't get to use your great interface. But if I had a special token authentication share link that they just click on and can see it, that would be pretty swell!

Not the end of the world if it can't be done. Exporting the track works good, it just requires that I help the end user a lot if they don't know how to import it. If the person is not tech savvy, this can be a large undertaking, especially if they are not physically with me for me to show them.

I am using version 1.0. The share button in the app works, but since my tracks are not public then they must log in to see them. If I give them a log in, then that takes time and makes all of my tracks visable to them.

P.S. some sort of token that expires after a day or after a view, or etc., would be great. Again, I love this server and app combo, thanks for making it!

**Comment by bfabiszewski** [comment]
I would like to add such feature to both client and server app. A way to mark individual tracks as private or public.
But it may take some time, before I find some time to do it.

**Comment by steven-omaha** [comment]
This feature would be highly appreciated by many!

**Comment by virtadpt** [comment]
Indeed!

**Comment by steven-omaha** [comment]
Hey there, I am still interested in this feature, but don't know nearly enough JS or PHP to implement this myself.

Could I maybe propose a "deal"? If I would create a PR for proper Docker integration (docker-compose.yml to deploy the webservice and the database in separate containers, see e.g. #136 and #144), would you implement this feature?

Totally ok if not. It's your project after all.

**Comment by bfabiszewski** [comment]
I want to implement this feature. Can't promise any deadline. I am busy lately. Hope to find some time soon.

Regarding docker, I created it only for testing purposes. I noticed some people started using it for production, so proper docker is definitely needed. I just don't have time to create and maintain it. For my testing purposes I just need a minimal docker, small and fast. If you want to work on production docker please reopen https://github.com/bfabiszewski/ulogger-server/issues/144.

**Comment by binarydad** [comment]
I would love a share option in general. I can't share my bike routes because it requires a login.

**Comment by virtadpt** [comment]
This would be a useful feature for me as well.  My particular use case is, if something bad happens (like a California wildfire spreads in unexpected directions) while I'm out and about, I'd like to be able to send a link (more accurately, one of my agents) to my family without their needing to log into my ulogger server install to see where I'm stuck.

**Comment by zag-adka** [comment]
I love this software, I use it on my smartphone, often offline and sometimes online with a simple docker install on my own virtual server.

It would be very nice to be able to share positions with friends or family, for two use cases:
- @alaskalinuxuser suggested to share the track afterwards, it would be very easy for the track author and the track viewers ;
- @virtadpt suggested to share at the beginning, for a sailing race or for safety : «If I don't come back tomorrow, please look at my position to send rescue team, but please don't track me, my friend»

I'm able to contribute to the code if I look a bit to the internals and it would be easier if you suggest a way to do it.

I will open another feature request but I describe it here because it can be related but doesn't depend on it. I'd like to be able to automatically encrypt the tracks with the user password (or something like this), so I could offer friends to record and upload a live track on my server (shared with a trusted third person), but without sharing the track with me, even in admin mode, if I'm not the trusted person.

**Comment by poggenpower** [comment]
I am also looking for this feature.
