### ISSUE TITLE
Remove Database from Dockerfile

### ISSUE THREAD

**Issue by MagicRB** [bfabiszewski/ulogger-server#144]
It is recommended that unless absolutely necessary a Dockerfile should only run one service. Also with the current configuration, the persistence of the data store is really cumbersome. I will write a new Dockerfile if you're interested in this change

**Comment by bfabiszewski** [comment]
Thanks for the comment.
The docker included in the project is designed only for integration tests. That's why I made a minimal setup that should be small and run fast. It is not suitable for production.
It would be nice to have a production docker that users could use to run the application. It could be separate from this repo. If you create such a docker I will link to it from the Readme. You may consider integrating this [pull request](https://github.com/bfabiszewski/ulogger-server/pull/136).
