### ISSUE TITLE
Unexpected End of Steam

### ISSUE THREAD

**Issue by Benjilein** [bfabiszewski/ulogger-server#149]
Dear Bartek

First of all: Thank you very much for setting up and maintaining such a wonderful project.  

Unfortunately, I cannot "upload" data anymore. If I try, I'll get the error: "Unexpected end of stream". After I created a new track, I set the Android client to "Live synchronization". The first three points were uploaded correctly. But with the next point, the I got "1 point behind" and "unexpected end of stream".
What I tried (with always the same error):
- Manual Upload
- Disable live sync and manual upload
- Delete track on server and manual upload. 

Do you have any idea what causes this error or a hint for further investigations? :-) 

Br,
Benji

**Comment by bfabiszewski** [comment]
Which client and server version?
Which Android version?
Were you uploading any positions with images?

If you deleted the track on the server the uploading will not work any more. You have to also delete the track on the client.
Try with a new track on the client and check if the problem will repeat.

**Comment by Benjilein** [comment]
Thank you for your fast replay: 
Server: 1.1-beta
Client: 3.3
Android: 7.1.1

The track from today just had the same error. 
Based on your questions, I made some experiments (I set MinDIstance=No; MinTime=30s): 
- Point upload (synchronize) works until I add the first way-point with a picture
- No difference between "live synchonization" and manual upload (button)
- No difference if geo-location is embedded in the pictures or not
- No difference between "Take photo" and "Choose from library"
- Upload-Folder stays empty

Maybe this helps to narrow it down. 

Thank you very great support. :-)

**Comment by bfabiszewski** [comment]
Thanks for the info.
I assume it is image upload problem then. And it doesn't matter if image is from camera or from library.
What is the uploaded image size setting in client app preferences?
Did you try to change that image size setting? Does it help if you set smaller image size for example? Or if set to "actual size"?

**Comment by Benjilein** [comment]
With the last experiments, I either used "800px" or "1080px". 
Now I experimented with: 
- Actual Size
- Actual Size + Camera Resolution 2M, 4M, 16M
- Other: 400, 600
- Camera Settings: HDR, HDR+, No HDR
--> Always the same error "unexpected end of stream". 


What works: 
Export track --> Copy to PC --> Import Track at server --> Edit Position --> Add (original) Image manually. 

Would it help, if I send you some pictures?

**Comment by bfabiszewski** [comment]
Thanks, the pictures will not help me.
I forgot to tell you that while testing different image sizes you need to recreate track before each test. Because the setting is used at the moment you take picture or select it from the gallery. The application resamples the image and saves it to temporary location. If you take a picture and later try to change the setting before uploading it will not have any effect. Make sure your tests use different settings at the time of acquiring the image.
What is the device you are using?
Did you try to upload images from another device?
Do you have any other server so that you could test uploading images to that server?
I am still not sure if it is a server or client issue. It looks more like a client problem, but I don't have any clue why it wouldn't work with you particular device.
It would be helpful to exclude server issue. If you don't have any other way to check whether it is a server problem you could set up a µlogger test account and send me the credentials by email (you will find it on my [webpage](https://www.fabiszewski.net)) so that I can test upload. You could also try the upload from emulator if you don't have any other device.

**Comment by Benjilein** [comment]
Thank you for the information. I'll look into the points during this week and give you feedback.

**Comment by bfabiszewski** [comment]
No feedback, so I am closing it now. 
Feel free to reopen if you have any news. 
For the moment I assume the problem was related to your environment setup.
