### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vsatmydynipnet** [bfabiszewski/ulogger-server#154]
First of all, thank you for this cool peace of software. I am migrating my devices from Traccar to ulogger and it really works fine.

There is 1 thing i am missing hard:

- let some devices be viewed from other users without being a administrator:

e.g. I have 4 devices: A1, A2, B1, B2 which all have their accounts to report. But e.g. Account A1 should be able to se A2 in the Web view too and B1 should be able to see A1, A2, B1, B2 . 

Thank you!

**Comment by bfabiszewski** [comment]
Thanks for your comments!
That would require having users organized in groups. I don't think I will create such feature any time soon.
This application is mostly dedicated to private users that want to record their tracks with respect to their privacy.
Targeting larger organizations is rather out of scope, mainly due to lack of time.
