### ISSUE TITLE
How to make my account accessible while unlogged ?

### ISSUE THREAD

**Issue by stemy2** [bfabiszewski/ulogger-server#241]
Hello,

I'd like to use the app to show to my fiends in real time without forcing them to use my login and my password for more usability. What should i do to make it possible ?

**Comment by bfabiszewski** [comment]
You can either make the server open for anyone to view. This is how [the demo server ](https://ulogger.lima.zone)is configured (public tracks: yes, require authorization: no).
The other option is to require login in order to view tracks. In this case you have to setup an account for your friends  (public tracks: yes, require authorization: yes).

**Comment by stemy2** [comment]
The "public tracks" and "require authorization" are not present in my config file, and adding them manually doesn't change anything.

**Comment by bfabiszewski** [comment]
You have to change it in the user interface in Administration->Settings. You must be logged in as an admin user.
![Screenshot 2024-11-29 at 11 24 12](https://github.com/user-attachments/assets/49d18c27-6c81-480b-8eb8-cbb57ad24322)

**Comment by stemy2** [comment]
I don't have a such option.
![Copie d'écran_20241129_134023](https://github.com/user-attachments/assets/1d18ea5f-1493-4b4e-96a4-54d7594cad14)
