### ISSUE TITLE
Data Import canceled with "something went wrong"

### ISSUE THREAD

**Issue by imothep666** [bfabiszewski/ulogger-server#30]
Trying to import gpx track finishes with error "something went wrong".  The MySql Tables positions and tracks are populated with data and the track is in the selection box on the web frontend.

Thanks.

**Comment by bfabiszewski** [comment]
So the import succeeds but the application still reports error.
Could you post the gpx file somewhere? You could anonymize it globally replacing all `lon` and `lat` attributes with `lon="0" lat="0"` for example. Where does the gpx file come from?

**Comment by imothep666** [comment]
The file was  created by OsmAnd+

Thanks.

[2017-06-11_12-39_Sun.gpx.txt](https://github.com/bfabiszewski/ulogger-server/files/1190566/2017-06-11_12-39_Sun.gpx.txt)

**Comment by bfabiszewski** [comment]
Thanks!

Your file imports fine on my development server. 
But I managed to reproduce the failure on the demo server. The problem there was however more general as imports were failing for any gpx file. It turned out that the demo server was badly configured. A directory for storing temporary files was missing. I corrected it.

Maybe that is also your problem?

**Comment by imothep666** [comment]
I have opened 127.0.0.1/client/index.php and the output was "/{"error":false}" - i use it on a local systemand the ulogger folder and all subdirectories have read write and execute rights.

Thanks

**Comment by bfabiszewski** [comment]
Your reply probably belongs to another issue :)
Please move it to bfabiszewski/ulogger-android#17

**Comment by imothep666** [comment]
sorry .. what do u think is missing - i have pulled the repository directly from github to my webserver and the server has 777 on all files and directories in the folder (server runs only in the local network))

**Comment by bfabiszewski** [comment]
Difficult to say. Now I can't reproduce your issue. I had similar problem which was caused by wrong web server configuration. 
But it seems that you problem is different, because you mentioned that despite the error message track is successfully imported into database.
Look for some errors or warnings in your server logs.

**Comment by imothep666** [comment]
Thank you for your support - i was able to fix the issues by deleting and repulling the repository.

**Comment by bfabiszewski** [comment]
Great!
