### ISSUE TITLE
error handling in uPosition::add()

### ISSUE THREAD

**Issue by r00t-** [bfabiszewski/ulogger-server#32]
the code in uPosition::add() catches various error-cases,
but returns just bool(false) in *any* error-case, does not even log the error details.
the calling code in client.php will then only report the useless string "Server error".

this makes errors there needlessly hard to debug.

i might provide a patch, but this is really an architectural issue, as there is no provision for returning error details in your api.
i would need to know how you would prefer to handle this.
(die()? throw exceptions? return an object containing (error,id)? return an error string and use is_numeric() in caller?)

if you think those errors "will never happen anyway", here's what i did:
in the android client:
* configure some server ( i used the demo server)
* create a track and log some points.
* change the server  to a different server (my newly installed ulogger server).
* try to log some more points
* the client will assume the track already exists on the server, and try logging positions into a non-existant track, reporting "Server error".

(you might also considers this a bug in the client and fix it there - but you can not know if the user is setting a new address of the same old server or is switching to a different server)

**Comment by bfabiszewski** [comment]
Thanks for feedback!

I realize the error handling must be improved. I was affected myself a few times by this issue. The reason that I didn't do it is not that I believe it "will never happen" but I simply didn't have time :)

What do you think about such solution?
- add $error string property to uPosition class (empty by default)
- each method of the class, in case of error, will set error message to $error property 
- caller will be able to get detailed error message in case of failure (by calling getError() method or maybe even directly accessing $error property). The detailed message (if any) could be appended to "Server error" message.
Similar solution is used in php mysqli class. Then we could use this approach also in other classes in our project.

From your propositions I would prefer exceptions. I don't like the idea of returning object or error string. But implementing exceptions would be a bit more complicated. The solution I proposed above is simple to implement and can be introduced gradually, where needed, without breaking current behaviour. What do you think?

Regarding the particular error when changing server in the middle track logging. I was affected by this also. The problem is however more difficult, because it is also possible that you change the server and don't get any error message. It may happen if on the other server there is a track with the same id belonging to the same user. The positions will be mistakenly appended to this track. I think the best solution to this kind of problem is to display warning in the client when user tries to change the server URL while having open track that was already uploaded. If you can please report the problem to ulogger-android issues. This is not a high priority bug but should be resolved eventually.

**Comment by r00t-** [comment]
for some more feedback:
this is mostly a question of software architecture.
and the main deciding factor is (imho) how much time you want to spend on just that.
you could ofcourse turn it into an academic exercise of implementing your own framework, if you have the time and motivation.
or you could implement it on top of some existing framework, that provides error-handling conventions. a very popular choice. which could also be an exercise in learning to use that framework.
given the size of this project, i would go for a cheap solution (maybe even the ad-hoc solution of returning an array).
my next choice would be exceptions, specifically because they require least code changes. as most errors are fatal anyway, you can just throw them in any low-level code, and have a single try/catch-block at the top level, that catches the error and provides and appropriately formatted message to the client, without needing any error-handling code in between to pass the error up.

**Comment by bfabiszewski** [comment]
Sorry for late answer, but I've been away.
As we both agree that exceptions are a good solution let's throw exceptions :)
Do you want to provide PR for that?

I've just pushed some changes from my local branch including some unit tests. Some of the test will have to be modified to assert that methods throw exceptions instead of returning boolean value.
