### ISSUE TITLE
Installation from command-line

### ISSUE THREAD

**Issue by anmol26s** [bfabiszewski/ulogger-server#38]
Hi
I created an app package for [Yunohost](https://yunohost.org) which will help people who like self-hosting.
Here is the app link: https://github.com/YunoHost-Apps/ulogger_ynh

I have used curl to setup the database. https://github.com/YunoHost-Apps/ulogger_ynh/blob/master/scripts/install#L143 and hashing the password and then running mysql query to input the admin user to the database. https://github.com/YunoHost-Apps/ulogger_ynh/blob/master/scripts/install#L60. 
Is there a better way this can be done?
While updating the app, will it be enough to backup config.php and unzip the new version and then restoring the config.php to it?

**Comment by bfabiszewski** [comment]
Thanks!

I think your setup is ok. Only make sure to disable setup script after running it.

Or alternatively you could skip running setup script. The only thing the setup script does is setting up database tables and adding first user. If you are running your own script you could just install db tables and add first user to database and mark it as admin in config.php.

When upgrading backing up config file should be ok, as long as there are no backwards incompatible changes in config options. The same applies to database tables.

BTW I will publish new release in a moment to include all the changes since last one. There will be some changes to config file in the release, as new version introduces openlayers 3 support and adding new tile layers from config file
