### ISSUE TITLE
#1068 - Multiple primary key defined 

### ISSUE THREAD

**Issue by Yogosh** [bfabiszewski/ulogger-server#8]
I get this error when trying to import .sql file.

SQL query:
--
-- Indexes for dumped tables
--

--
-- Indexes for table `positions`
--
ALTER TABLE `positions`
  ADD PRIMARY KEY (`id`), ADD KEY `index_trip_id` (`track_id`), ADD KEY `index_user_id` (`user_id`);

MySQL said:
#1068 - Multiple primary key defined

I don't know much about sql so please help if you can.
Thanks!

**Comment by bfabiszewski** [comment]
I noticed there was a typo in [ulogger.sql](https://github.com/bfabiszewski/ulogger-server/blob/master/scripts/ulogger.sql) script. I corrected it. Please try again, but first make sure to delete ulogger database (DROP DATABASE ulogger). 
It was probably partially created and you are seeing the error because you are trying to add the key second time.

**Comment by Yogosh** [comment]
Everything works now, thanks!

**Comment by bfabiszewski** [comment]
Great it works. Thanks for reporting this issue!
