### ISSUE TITLE
Last positions don't work

### ISSUE THREAD

**Issue by srayneau** [bfabiszewski/ulogger-server#87]
Hello,
I updated the 0.5-beta version to 1.0-beta and the last position function seems to not work.
If I use the 0.5-beta version it works directly.
The problem does not seem to come from the database.

Do you have an idea ?

**Comment by bfabiszewski** [comment]
What exactly happens when you choose last position option?
Are there any errors in javascript console or web server logs?
Did you try to clear browser cache to make sure latest scripts are used?

If you look at [demo server](http://ulogger-demo.herokuapp.com), last positions seem to work fine.
Same at my test sites with different settings.

**Comment by srayneau** [comment]
You are certainly right a problem of cache, I do not have the problem with firefox, only with chrome.
Excuse me I never think of browser caches ... sorry
