### ISSUE TITLE
Auto tracks

### ISSUE THREAD

**Issue by NohWayJose** [bfabiszewski/ulogger-server#99]
A usability issue, rather than a technical one. As an experiment I've been tracking my daughter's phone (with her knowledge), as a proof of tech for when we go to music festivals and other crowded places. Unfortunately I have found that the tracks just get more and more like a bird's nest,

Please will you add a setting to generate a new track periodically. This could be simple to start with, just starting a new track at midnight, (name based on the track template). 

Later versions could:
1/ have explicit start and end periods (along the lines of a calendar event, with a repeat option?)
2/ Trigger a new track in response to other GPS  events (such as being within a certain distance of a coordinate position or being too far from one)
3/ Detecting a specific bluetooth device, such as the headphones you run in
4/ A new track triggered on the client by the server or even just a way of querying/filtering the data-set  at the server end to dynamically (and on demand) break down the tracks into more manageable and meaningful sections

**Comment by bfabiszewski** [comment]
Thanks for the comment. 
I designed the app mainly to record short outdoor activities, like trekking, cycling excursions. I know some people use the app for multiday activities, but I am not convinced I want to go in this direction. 
The same applies to geofencing or detecting bluetooth devices. I would prefer to keep the app simple rather than changing it into a Swiss army knife.

For starting new tracks periodically or triggering it by some other events you could use an application like Tasker. Μy µlogger offers [interface](https://github.com/bfabiszewski/ulogger-android#automating) for integration with such tools.

Better database filtering on server is a good idea that is on my todo list.

**Comment by Evidlo** [comment]
@NohWayJose 1-3 can all be accomplished by using Easer to trigger a new µLogger track.
